/* global window */
// =====================================================================
// Portfolio item data — compact, separated for tractability.
// Each item: {id, cat, tag, tool, title, desc, price, likes, views,
//             featured?, buildable?, thumb: <key>, site?: <config>}
// =====================================================================

const PORTFOLIO_ITEMS = [
  // ============================================================
  // 웹사이트  (24)  — every site is a tiny scrollable mini-site
  // ============================================================
  { id:"w01", cat:"웹사이트", tag:"SaaS 랜딩", tool:"Claude 4.5 Sonnet", title:"미니멀 SaaS 랜딩 페이지", desc:"보라 그라데이션 + 화이트 카드 베이스의 모던 SaaS 홈.",
    price:4900, likes:218, views:"1.2K", featured:true, buildable:true,
    thumb:"site", site:{ key:"saas-violet", url:"sulab.ai" } },
  { id:"w02", cat:"웹사이트", tag:"Linear", tool:"Claude 4.5 Sonnet", title:"다크 모드 개발자 도구 홈", desc:"Linear 풍의 깔끔한 다크 SaaS — 그리드 + 키보드 단축키 강조.",
    price:5400, likes:412, views:"3.1K", buildable:true,
    thumb:"site", site:{ key:"saas-dark", url:"linear-clone.dev" } },
  { id:"w03", cat:"웹사이트", tag:"D2C", tool:"GPT-4o", title:"한국형 D2C 쇼핑몰 홈", desc:"패션 D2C에 최적화. 그리드 컬렉션 + 룩북 + 후기.",
    price:5900, likes:284, views:"2.0K", buildable:true,
    thumb:"site", site:{ key:"shop-fashion", url:"brandlab.kr" } },
  { id:"w04", cat:"웹사이트", tag:"이커머스", tool:"Claude 4.5 Sonnet", title:"유기농 식품 이커머스", desc:"녹색 톤의 그린 이커머스 — 신선 그로서리 컬렉션.",
    price:5400, likes:188, views:"1.4K", buildable:true,
    thumb:"site", site:{ key:"shop-green", url:"freshfarm.co" } },
  { id:"w05", cat:"웹사이트", tag:"포트폴리오", tool:"Claude 4.5 Sonnet", title:"디자인 에이전시 포트폴리오", desc:"타이포 중심의 에이전시 사이트 — 큼직한 헤드라인 + 케이스 그리드.",
    price:4900, likes:367, views:"2.7K", featured:true, buildable:true,
    thumb:"site", site:{ key:"agency", url:"studio-aurora.kr" } },
  { id:"w06", cat:"웹사이트", tag:"모바일 앱", tool:"Claude 4.5 Sonnet", title:"핀테크 앱 마케팅 페이지", desc:"토스 스타일 풀-블리드 색상 섹션 + 폰 목업.",
    price:4400, likes:142, views:"1.0K", buildable:true,
    thumb:"site", site:{ key:"fintech", url:"toss-clone.app" } },
  { id:"w07", cat:"웹사이트", tag:"레스토랑", tool:"GPT-4o", title:"파인 다이닝 레스토랑 홈", desc:"따뜻한 톤 + 메뉴 갤러리 + 예약 위젯.",
    price:3900, likes:96, views:"680", buildable:true,
    thumb:"site", site:{ key:"restaurant", url:"olivenoir.kr" } },
  { id:"w08", cat:"웹사이트", tag:"블로그", tool:"Claude 4.5 Sonnet", title:"미디엄 스타일 테크 블로그", desc:"센터 정렬 긴 글 레이아웃 + 아티클 카드 그리드.",
    price:2900, likes:73, views:"540", buildable:true,
    thumb:"site", site:{ key:"blog-medium", url:"reads.dev" } },
  { id:"w09", cat:"웹사이트", tag:"AI 챗봇", tool:"Claude 4.5 Sonnet", title:"AI 챗봇 SaaS 페이지", desc:"채팅 UI 데모 + 기능 그리드 — 다크/네이비 베이스.",
    price:5400, likes:218, views:"1.8K", buildable:true,
    thumb:"site", site:{ key:"ai-chat", url:"askmind.ai" } },
  { id:"w10", cat:"웹사이트", tag:"창작자", tool:"GPT-4o", title:"뉴스레터 작가 랜딩", desc:"센터 정렬 + 구독 폼 + 최근 글 카드 — 세리프 타이포.",
    price:2400, likes:108, views:"720",
    thumb:"site", site:{ key:"creator", url:"jiwon.kr" } },
  { id:"w11", cat:"웹사이트", tag:"음악", tool:"Claude 4.5 Sonnet", title:"음악 스트리밍 앱 랜딩", desc:"보라/핑크 그라데이션 + 앨범 그리드 + 플레이어 위젯.",
    price:4400, likes:284, views:"2.2K", buildable:true,
    thumb:"site", site:{ key:"music", url:"flux-music.app" } },
  { id:"w12", cat:"웹사이트", tag:"여행", tool:"Claude 4.5 Sonnet", title:"여행 예약 플랫폼 홈", desc:"풀-블리드 풍경 헤로 + 검색 바 + 추천 카드.",
    price:5900, likes:172, views:"1.3K", buildable:true,
    thumb:"site", site:{ key:"travel", url:"haru-travel.co" } },
  { id:"w13", cat:"웹사이트", tag:"문서", tool:"Claude 4.5 Sonnet", title:"개발자 문서 사이트", desc:"사이드바 + 본문 + 코드 블록 — Stripe Docs 스타일.",
    price:3400, likes:142, views:"940", buildable:true,
    thumb:"site", site:{ key:"docs", url:"docs.sulab.ai" } },
  { id:"w14", cat:"웹사이트", tag:"부동산", tool:"GPT-4o", title:"부동산 매물 플랫폼", desc:"지도 + 매물 리스트 + 필터 칩 — 모던한 그레이 톤.",
    price:5400, likes:78, views:"610",
    thumb:"site", site:{ key:"realestate", url:"haus.kr" } },
  { id:"w15", cat:"웹사이트", tag:"교육", tool:"Claude 4.5 Sonnet", title:"온라인 강의 플랫폼", desc:"강의 그리드 + 강사 카드 + 진도율 위젯.",
    price:4900, likes:204, views:"1.5K", buildable:true,
    thumb:"site", site:{ key:"edu", url:"learn.io" } },
  { id:"w16", cat:"웹사이트", tag:"게임", tool:"Claude 4.5 Sonnet", title:"인디 게임 출시 페이지", desc:"풀-블리드 다크 + 트레일러 + 캐릭터 카드.",
    price:4400, likes:328, views:"2.4K", featured:true,
    thumb:"site", site:{ key:"game", url:"echoes-game.io" } },
  { id:"w17", cat:"웹사이트", tag:"사진가", tool:"Claude 4.5 Sonnet", title:"사진가 포트폴리오", desc:"풀-블리드 이미지 그리드 + 미니멀 캡션.",
    price:3400, likes:156, views:"1.1K",
    thumb:"site", site:{ key:"photo", url:"minlee.studio" } },
  { id:"w18", cat:"웹사이트", tag:"Web3", tool:"Claude 4.5 Sonnet", title:"NFT 컬렉션 민트 페이지", desc:"네온 다크 + 카운트다운 + 컬렉션 갤러리.",
    price:4900, likes:218, views:"1.7K",
    thumb:"site", site:{ key:"nft", url:"shards.xyz" } },
  { id:"w19", cat:"웹사이트", tag:"헬스케어", tool:"GPT-4o", title:"메디컬 클리닉 홈", desc:"화이트/민트 톤 + 진료과목 카드 + 의료진 프로필.",
    price:3900, likes:64, views:"480", buildable:true,
    thumb:"site", site:{ key:"medical", url:"miracle-clinic.kr" } },
  { id:"w20", cat:"웹사이트", tag:"리테일", tool:"Claude 4.5 Sonnet", title:"노트북 가전 상세 페이지", desc:"갤러리 + 옵션 선택 + 후기 + 추천 — PDP 풀패키지.",
    price:4400, likes:124, views:"880", buildable:true,
    thumb:"site", site:{ key:"pdp-tech", url:"shop.electrica.kr" } },
  { id:"w21", cat:"웹사이트", tag:"이벤트", tool:"Claude 4.5 Sonnet", title:"컨퍼런스 행사 페이지", desc:"카운트다운 + 스피커 그리드 + 어젠다 + 티켓.",
    price:3900, likes:96, views:"720",
    thumb:"site", site:{ key:"event", url:"ai-conf-2026.kr" } },
  { id:"w22", cat:"웹사이트", tag:"커뮤니티", tool:"Claude 4.5 Sonnet", title:"디스코드 스타일 커뮤니티 홈", desc:"보라 베이스 + 채널 리스트 + 멤버 카드.",
    price:3400, likes:142, views:"1.0K",
    thumb:"site", site:{ key:"community", url:"circle.gg" } },
  { id:"w23", cat:"웹사이트", tag:"채용", tool:"GPT-4o", title:"스타트업 채용 페이지", desc:"팀 사진 + 가치 + JD 리스트 + 지원 폼.",
    price:2900, likes:54, views:"380",
    thumb:"site", site:{ key:"hiring", url:"join.sulab.ai" } },
  { id:"w24", cat:"웹사이트", tag:"체육관", tool:"Claude 4.5 Sonnet", title:"피트니스 짐 랜딩", desc:"강렬한 다크 + 노란 액센트 + 트레이너 + 클래스 시간표.",
    price:3400, likes:188, views:"1.4K",
    thumb:"site", site:{ key:"gym", url:"forge-fit.kr" } },

  // ============================================================
  // 이미지  (22)
  // ============================================================
  { id:"i01", cat:"이미지", tag:"초상화", tool:"Midjourney v6", title:"수채화풍 동양 여성 인물",
    desc:"파스텔 톤, 잉크 번짐 효과, 한지 배경. 표지/앨범용.",
    price:2900, likes:412, views:"3.8K", featured:true, thumb:"watercolor" },
  { id:"i02", cat:"이미지", tag:"풍경", tool:"DALL-E 3", title:"네온 사이버펑크 도쿄",
    desc:"비 오는 밤, 분홍/시안 네온 도시 — 영화같은 와이드샷.",
    price:1900, likes:538, views:"5.1K", featured:true, thumb:"cyberpunk" },
  { id:"i03", cat:"이미지", tag:"음식", tool:"Midjourney v6", title:"파인 다이닝 파스타 플레이팅",
    desc:"오버헤드 + 자연광 + 무광 도자기 — 메뉴/SNS용.",
    price:2400, likes:287, views:"2.3K", thumb:"food" },
  { id:"i04", cat:"이미지", tag:"캐릭터", tool:"Midjourney v6", title:"픽사 스타일 캐릭터 시트 4컷",
    desc:"정면·측면·뒷면·표정 시트 — IP 개발용.",
    price:4900, likes:321, views:"2.7K", thumb:"characterSheet" },
  { id:"i05", cat:"이미지", tag:"풍경", tool:"Midjourney v6", title:"동양화 산수화 풍경",
    desc:"먹과 한지 — 안개 자욱한 산봉우리 + 폭포.",
    price:2400, likes:204, views:"1.6K", thumb:"watercolor" },
  { id:"i06", cat:"이미지", tag:"초상화", tool:"DALL-E 3", title:"필름 룩 인물 사진",
    desc:"35mm 필름 그레인 + 자연광 + 80년대 무드.",
    price:1900, likes:178, views:"1.4K", thumb:"watercolor" },
  { id:"i07", cat:"이미지", tag:"풍경", tool:"Midjourney v6", title:"사막 위 보름달",
    desc:"미니멀 + 골든 아워 + 광활한 사막 + 거대 달.",
    price:2100, likes:265, views:"2.0K", thumb:"cyberpunk" },
  { id:"i08", cat:"이미지", tag:"제품 컷", tool:"Midjourney v6", title:"화장품 제품 컷",
    desc:"파스텔 배경 + 부드러운 그림자 + 미니멀 스타일링.",
    price:2400, likes:142, views:"1.0K", thumb:"food" },
  { id:"i09", cat:"이미지", tag:"건축", tool:"Midjourney v6", title:"브루탈리즘 건축",
    desc:"콘크리트 + 강한 그림자 + 모노톤 — 잡지 표지급.",
    price:2900, likes:332, views:"2.5K", thumb:"cyberpunk" },
  { id:"i10", cat:"이미지", tag:"패션", tool:"Midjourney v6", title:"하이엔드 패션 룩북",
    desc:"보그 표지 스타일 — 강렬한 조명 + 미니멀 배경.",
    price:3400, likes:418, views:"3.1K", featured:true, thumb:"watercolor" },
  { id:"i11", cat:"이미지", tag:"음식", tool:"Midjourney v6", title:"한식 정찬 오버헤드",
    desc:"백자 그릇 + 청자 트레이 + 자연광 — 한정식 컷.",
    price:2400, likes:204, views:"1.6K", thumb:"food" },
  { id:"i12", cat:"이미지", tag:"캐릭터", tool:"Midjourney v6", title:"3D 픽셀 캐릭터 컬렉션",
    desc:"보크셀 스타일 RPG 캐릭터 12종 — 게임 IP용.",
    price:3900, likes:186, views:"1.3K", thumb:"characterSheet" },
  { id:"i13", cat:"이미지", tag:"풍경", tool:"DALL-E 3", title:"극지방 오로라",
    desc:"보라/녹색 오로라 + 설원 + 외로운 텐트.",
    price:2100, likes:228, views:"1.7K", thumb:"cyberpunk" },
  { id:"i14", cat:"이미지", tag:"제품 컷", tool:"Midjourney v6", title:"럭셔리 시계 광고",
    desc:"어두운 배경 + 핀 라이팅 + 메탈 디테일 클로즈업.",
    price:2900, likes:154, views:"1.1K", thumb:"food" },
  { id:"i15", cat:"이미지", tag:"패션", tool:"Midjourney v6", title:"스트리트웨어 룩북",
    desc:"네온 사인 거리 + 와이드 앵글 + 야간 촬영 룩.",
    price:2900, likes:312, views:"2.3K", thumb:"cyberpunk" },
  { id:"i16", cat:"이미지", tag:"동물", tool:"Midjourney v6", title:"고양이 초상 시리즈",
    desc:"렘브란트 조명 + 깊은 검정 배경 + 시그니처 룩.",
    price:1900, likes:486, views:"4.2K", thumb:"watercolor" },
  { id:"i17", cat:"이미지", tag:"우주", tool:"DALL-E 3", title:"광활한 우주 성운",
    desc:"보라/핑크 가스 성운 + 별의 무리 + 행성 실루엣.",
    price:2400, likes:362, views:"2.8K", thumb:"cyberpunk" },
  { id:"i18", cat:"이미지", tag:"빈티지", tool:"Midjourney v6", title:"70s 폴라로이드 무드",
    desc:"색바램 + 따뜻한 톤 + 그레인 — 회상의 한 컷.",
    price:1900, likes:204, views:"1.5K", thumb:"watercolor" },
  { id:"i19", cat:"이미지", tag:"음식", tool:"Midjourney v6", title:"디저트 카페 무드",
    desc:"케이크 + 라떼 아트 + 햇살 — 카페 인스타용.",
    price:1900, likes:178, views:"1.3K", thumb:"food" },
  { id:"i20", cat:"이미지", tag:"캐릭터", tool:"Midjourney v6", title:"애니메이션 영웅 컨셉",
    desc:"지브리 풍 인물 컨셉 — 자연 배경 + 부드러운 색감.",
    price:3400, likes:524, views:"4.1K", featured:true, thumb:"characterSheet" },
  { id:"i21", cat:"이미지", tag:"풍경", tool:"Midjourney v6", title:"한국 시골 가을 풍경",
    desc:"단풍 + 한옥 + 안개 — 회화적 합성.",
    price:2100, likes:262, views:"1.9K", thumb:"watercolor" },
  { id:"i22", cat:"이미지", tag:"제품 컷", tool:"Midjourney v6", title:"향수 광고 컷",
    desc:"앰버 톤 배경 + 물방울 + 부드러운 빛 — 잡지급.",
    price:2400, likes:144, views:"1.0K", thumb:"food" },

  // ============================================================
  // 카피  (20)
  // ============================================================
  { id:"c01", cat:"카피", tag:"광고 카피", tool:"Claude 4.5 Haiku", title:"패션 브랜드 인스타 캠페인 5종",
    desc:"캐주얼 톤 인스타 캡션 5개 변형 + 해시태그 세트.", price:1900, likes:96, views:"640", thumb:"igCopy" },
  { id:"c02", cat:"카피", tag:"SEO 콘텐츠", tool:"GPT-4o", title:"SEO 최적화 블로그 글 (2,000자)",
    desc:"키워드 분석 → H1~H3 + 메타 디스크립션까지.", price:3900, likes:73, views:"560", featured:true, thumb:"seoBlog" },
  { id:"c03", cat:"카피", tag:"이메일", tool:"Claude 4.5 Haiku", title:"환영 이메일 시퀀스 5통",
    desc:"가입 후 첫 주에 보내는 따뜻한 환영 시퀀스.", price:2400, likes:128, views:"890", thumb:"igCopy" },
  { id:"c04", cat:"카피", tag:"제품 설명", tool:"GPT-4o", title:"이커머스 제품 설명 템플릿",
    desc:"감성적 + 실용적 정보 — 상세페이지용.", price:1900, likes:204, views:"1.5K", thumb:"seoBlog" },
  { id:"c05", cat:"카피", tag:"광고 카피", tool:"Claude 4.5 Sonnet", title:"메타 광고 헤드라인 30종",
    desc:"전환 최적화 헤드라인 풀 — A/B 테스트 즉시.", price:2400, likes:218, views:"1.8K", thumb:"igCopy" },
  { id:"c06", cat:"카피", tag:"브랜드", tool:"Claude 4.5 Sonnet", title:"브랜드 보이스 가이드",
    desc:"톤·매너 정의 + 좋은/나쁜 예시 + 단어 사전.", price:4400, likes:142, views:"980", featured:true, thumb:"seoBlog" },
  { id:"c07", cat:"카피", tag:"SEO 콘텐츠", tool:"GPT-4o", title:"롱폼 가이드 (5,000자)",
    desc:"심층 가이드 + 인포그래픽 위치 + 내부 링크.", price:4900, likes:96, views:"640", thumb:"seoBlog" },
  { id:"c08", cat:"카피", tag:"이메일", tool:"GPT-4o", title:"세일즈 콜드 메일 시퀀스",
    desc:"B2B SaaS용 5단계 시퀀스 — 답장률 검증됨.", price:3400, likes:178, views:"1.2K", thumb:"igCopy" },
  { id:"c09", cat:"카피", tag:"슬로건", tool:"Claude 4.5 Haiku", title:"브랜드 슬로건 50종",
    desc:"산업별 50개 슬로건 — 즉시 사용 가능.", price:1900, likes:262, views:"1.9K", thumb:"seoBlog" },
  { id:"c10", cat:"카피", tag:"광고 카피", tool:"Claude 4.5 Haiku", title:"틱톡 후킹 스크립트 10종",
    desc:"3초 안에 시청 유지 — 후킹 패턴 10종.", price:2400, likes:332, views:"2.5K", thumb:"igCopy" },
  { id:"c11", cat:"카피", tag:"제품 설명", tool:"GPT-4o", title:"앱스토어 설명 템플릿",
    desc:"전환률 높은 앱스토어 설명 + 키워드 최적화.", price:1900, likes:108, views:"720", thumb:"seoBlog" },
  { id:"c12", cat:"카피", tag:"이메일", tool:"GPT-4o", title:"리뷰 요청 이메일",
    desc:"답장률 35% 검증 — 구매 후 일주일 시점 발송.", price:1900, likes:142, views:"990", thumb:"igCopy" },
  { id:"c13", cat:"카피", tag:"보도자료", tool:"GPT-4o", title:"보도자료 템플릿",
    desc:"투자 유치/제품 출시/협업 발표 3종 템플릿.", price:2900, likes:64, views:"420", thumb:"seoBlog" },
  { id:"c14", cat:"카피", tag:"광고 카피", tool:"Claude 4.5 Haiku", title:"네이버 키워드 광고 200종",
    desc:"검색 의도별 키워드 광고 카피 풀.", price:2400, likes:96, views:"680", thumb:"igCopy" },
  { id:"c15", cat:"카피", tag:"슬로건", tool:"Claude 4.5 Sonnet", title:"카피 한 줄 정리법",
    desc:"긴 카피를 임팩트 있는 한 줄로 다듬는 프롬프트.", price:2400, likes:178, views:"1.3K", thumb:"seoBlog" },
  { id:"c16", cat:"카피", tag:"브랜드", tool:"Claude 4.5 Sonnet", title:"브랜드 스토리텔링 프레임",
    desc:"창업 스토리를 3분 영상 스크립트로 변환.", price:3400, likes:142, views:"940", thumb:"seoBlog" },
  { id:"c17", cat:"카피", tag:"제품 설명", tool:"Claude 4.5 Haiku", title:"마켓플레이스 셀러 설명",
    desc:"쿠팡/지마켓용 — 빠른 스캔 + 키워드 풍부.", price:1900, likes:78, views:"540", thumb:"seoBlog" },
  { id:"c18", cat:"카피", tag:"광고 카피", tool:"GPT-4o", title:"링크드인 광고 카피",
    desc:"B2B 결정자 타겟 — 전문성 + 데이터 강조.", price:2400, likes:112, views:"830", thumb:"igCopy" },
  { id:"c19", cat:"카피", tag:"이메일", tool:"GPT-4o", title:"뉴스레터 오프닝 50종",
    desc:"열어보고 싶게 만드는 첫 문장 50종.", price:1900, likes:204, views:"1.6K", thumb:"igCopy" },
  { id:"c20", cat:"카피", tag:"SEO 콘텐츠", tool:"GPT-4o", title:"FAQ 페이지 자동 생성",
    desc:"제품 정보 입력 → 검색 의도별 FAQ 자동 생성.", price:2900, likes:88, views:"640", thumb:"seoBlog" },

  // ============================================================
  // 코드  (20)
  // ============================================================
  { id:"k01", cat:"코드", tag:"React", tool:"Claude 4.5 Sonnet", title:"접근성 완비 Button 컴포넌트",
    desc:"shadcn 스타일 + 키보드 / 스크린리더 / 로딩.", price:2900, likes:156, views:"1.4K", featured:true, thumb:"reactCode" },
  { id:"k02", cat:"코드", tag:"React", tool:"Claude 4.5 Sonnet", title:"데이터 테이블 컴포넌트",
    desc:"정렬/필터/페이지네이션/선택 — TanStack Table 기반.", price:4400, likes:264, views:"2.1K", thumb:"reactCode" },
  { id:"k03", cat:"코드", tag:"API", tool:"GPT-4o", title:"REST API 보일러플레이트",
    desc:"Hono + Drizzle + Zod — 3분 안에 API 시작.", price:3900, likes:218, views:"1.6K", thumb:"reactCode" },
  { id:"k04", cat:"코드", tag:"Tailwind", tool:"Claude 4.5 Haiku", title:"Tailwind 다크 모드 셋업",
    desc:"system 우선 + 토글 + 색상 토큰 — 한 번에.", price:1900, likes:142, views:"1.1K", thumb:"reactCode" },
  { id:"k05", cat:"코드", tag:"React", tool:"Claude 4.5 Sonnet", title:"드래그 가능한 칸반 보드",
    desc:"dnd-kit + 키보드 접근성 + 다중 컬럼.", price:4400, likes:312, views:"2.5K", thumb:"reactCode" },
  { id:"k06", cat:"코드", tag:"Next.js", tool:"Claude 4.5 Sonnet", title:"Next.js 14 인증 보일러플레이트",
    desc:"Auth.js + 이메일/소셜/매직링크 + middleware.", price:4900, likes:284, views:"2.0K", thumb:"reactCode" },
  { id:"k07", cat:"코드", tag:"Three.js", tool:"Claude 4.5 Sonnet", title:"3D 제품 뷰어 컴포넌트",
    desc:"Three.js + React Three Fiber — GLTF 로더 포함.", price:5400, likes:172, views:"1.4K", thumb:"reactCode" },
  { id:"k08", cat:"코드", tag:"Tailwind", tool:"Claude 4.5 Haiku", title:"Tailwind 디자인 토큰 스타터",
    desc:"전체 디자인 시스템 색·spacing·shadow 토큰.", price:2400, likes:96, views:"680", thumb:"reactCode" },
  { id:"k09", cat:"코드", tag:"React", tool:"Claude 4.5 Sonnet", title:"채팅 UI 컴포넌트",
    desc:"메시지 리스트 + 입력창 + 타이핑 인디케이터.", price:3400, likes:204, views:"1.7K", thumb:"reactCode" },
  { id:"k10", cat:"코드", tag:"Python", tool:"GPT-4o", title:"FastAPI + LangChain 시작 키트",
    desc:"RAG 챗봇 백엔드 + 스트리밍 + 벡터DB 연결.", price:5900, likes:332, views:"2.6K", featured:true, thumb:"reactCode" },
  { id:"k11", cat:"코드", tag:"React", tool:"Claude 4.5 Sonnet", title:"모달 + 토스트 시스템",
    desc:"Radix 기반 — 큐 + 키보드 + 애니메이션.", price:2900, likes:144, views:"1.0K", thumb:"reactCode" },
  { id:"k12", cat:"코드", tag:"CSS", tool:"Claude 4.5 Haiku", title:"인터랙티브 호버 효과 12종",
    desc:"순수 CSS — 카드 틸트/버튼 매직/이미지 줌.", price:1900, likes:218, views:"1.8K", thumb:"reactCode" },
  { id:"k13", cat:"코드", tag:"API", tool:"GPT-4o", title:"OpenAI Responses API 클라이언트",
    desc:"스트리밍 + 함수 호출 + 멀티턴 + 에러 처리.", price:3400, likes:188, views:"1.3K", thumb:"reactCode" },
  { id:"k14", cat:"코드", tag:"DevOps", tool:"GPT-4o", title:"Dockerfile + CI 템플릿",
    desc:"Node 멀티스테이지 + GitHub Actions + 배포.", price:2400, likes:96, views:"720", thumb:"reactCode" },
  { id:"k15", cat:"코드", tag:"React", tool:"Claude 4.5 Sonnet", title:"폼 검증 + 자동저장",
    desc:"React Hook Form + Zod + 디바운스 자동저장.", price:3400, likes:178, views:"1.4K", thumb:"reactCode" },
  { id:"k16", cat:"코드", tag:"Mobile", tool:"Claude 4.5 Sonnet", title:"Expo + 인증 스타터",
    desc:"Expo Router + SecureStore + Tabs + 다국어.", price:4400, likes:142, views:"1.0K", thumb:"reactCode" },
  { id:"k17", cat:"코드", tag:"Tailwind", tool:"Claude 4.5 Haiku", title:"반응형 그리드 시스템",
    desc:"flex/grid 패턴 12종 — 한 줄로 복사.", price:1900, likes:262, views:"2.0K", thumb:"reactCode" },
  { id:"k18", cat:"코드", tag:"Python", tool:"GPT-4o", title:"PDF 자동 처리 파이프라인",
    desc:"PyMuPDF + 텍스트 추출 + 표 파싱 + 요약.", price:2900, likes:104, views:"780", thumb:"reactCode" },
  { id:"k19", cat:"코드", tag:"React", tool:"Claude 4.5 Sonnet", title:"무한 스크롤 + 가상화",
    desc:"TanStack Virtual — 10만 행 렌더링 60fps.", price:3400, likes:156, views:"1.2K", thumb:"reactCode" },
  { id:"k20", cat:"코드", tag:"Next.js", tool:"Claude 4.5 Sonnet", title:"Toss Payments 통합",
    desc:"결제 위젯 + 검증 + 웹훅 처리 — 한국 결제 완비.", price:4400, likes:208, views:"1.6K", thumb:"reactCode" },

  // ============================================================
  // 콘텐츠  (20)
  // ============================================================
  { id:"v01", cat:"콘텐츠", tag:"스토리보드", tool:"Claude 4.5 Sonnet", title:"30초 광고 영상 스토리보드",
    desc:"신제품 출시 영상 4컷 + 보이스오버.", price:3400, likes:88, views:"510", thumb:"storyboard" },
  { id:"v02", cat:"콘텐츠", tag:"유튜브", tool:"GPT-4o", title:"유튜브 영상 스크립트",
    desc:"10분 영상 풀 스크립트 + 챕터 + 키워드.", price:3900, likes:218, views:"1.7K", featured:true, thumb:"storyboard" },
  { id:"v03", cat:"콘텐츠", tag:"틱톡", tool:"Claude 4.5 Haiku", title:"틱톡 60초 스크립트",
    desc:"후킹 + 본론 + CTA — 60초 안에.", price:1900, likes:312, views:"2.5K", thumb:"storyboard" },
  { id:"v04", cat:"콘텐츠", tag:"팟캐스트", tool:"GPT-4o", title:"팟캐스트 에피소드 구성",
    desc:"30분 에피소드 — 오프닝 + 토픽 + 게스트 질문.", price:2900, likes:78, views:"540", thumb:"storyboard" },
  { id:"v05", cat:"콘텐츠", tag:"인포그래픽", tool:"Claude 4.5 Sonnet", title:"인포그래픽 컨셉 시트",
    desc:"데이터 → 시각화 컨셉 + 색상 + 레이아웃.", price:2400, likes:128, views:"890", thumb:"storyboard" },
  { id:"v06", cat:"콘텐츠", tag:"스토리보드", tool:"Claude 4.5 Sonnet", title:"앱 출시 영상 9컷",
    desc:"기능 강조형 9-컷 스토리보드 + 트랜지션.", price:4400, likes:172, views:"1.3K", thumb:"storyboard" },
  { id:"v07", cat:"콘텐츠", tag:"유튜브", tool:"GPT-4o", title:"유튜브 쇼츠 1주일 분량",
    desc:"동일 토픽에서 파생된 7개 쇼츠 아이디어.", price:2400, likes:262, views:"2.0K", thumb:"storyboard" },
  { id:"v08", cat:"콘텐츠", tag:"강의", tool:"Claude 4.5 Sonnet", title:"온라인 강의 커리큘럼",
    desc:"10시간 강의 — 챕터 + 실습 + 평가.", price:3900, likes:108, views:"720", thumb:"storyboard" },
  { id:"v09", cat:"콘텐츠", tag:"인포그래픽", tool:"GPT-4o", title:"연간 리포트 인포그래픽",
    desc:"숫자 → 시각화 — 12장 슬라이드 컨셉.", price:3400, likes:64, views:"480", thumb:"storyboard" },
  { id:"v10", cat:"콘텐츠", tag:"스토리보드", tool:"Claude 4.5 Sonnet", title:"브랜드 다큐 5분",
    desc:"창업 스토리 5분 다큐 + 인터뷰 질문.", price:4900, likes:142, views:"980", thumb:"storyboard" },
  { id:"v11", cat:"콘텐츠", tag:"틱톡", tool:"Claude 4.5 Haiku", title:"틱톡 챌린지 기획",
    desc:"브랜드 챌린지 — 진행 흐름 + 인플루언서 가이드.", price:2400, likes:218, views:"1.8K", thumb:"storyboard" },
  { id:"v12", cat:"콘텐츠", tag:"유튜브", tool:"GPT-4o", title:"유튜브 썸네일 카피 30종",
    desc:"클릭 유발 헤드라인 + 색상 가이드.", price:1900, likes:332, views:"2.6K", thumb:"storyboard" },
  { id:"v13", cat:"콘텐츠", tag:"스토리보드", tool:"Claude 4.5 Sonnet", title:"단편영화 시나리오",
    desc:"10분 단편영화 — 캐릭터 + 플롯 + 다이얼로그.", price:5400, likes:96, views:"640", thumb:"storyboard" },
  { id:"v14", cat:"콘텐츠", tag:"강의", tool:"Claude 4.5 Sonnet", title:"라이브 웨비나 진행 가이드",
    desc:"60분 웨비나 — 인트로 + 본론 + Q&A 흐름.", price:2900, likes:142, views:"990", thumb:"storyboard" },
  { id:"v15", cat:"콘텐츠", tag:"팟캐스트", tool:"GPT-4o", title:"인터뷰 질문 풀 50종",
    desc:"창업자/디자이너/CEO 인터뷰용 깊이 있는 질문.", price:2400, likes:178, views:"1.3K", thumb:"storyboard" },
  { id:"v16", cat:"콘텐츠", tag:"인포그래픽", tool:"Claude 4.5 Sonnet", title:"프로세스 다이어그램",
    desc:"복잡한 워크플로우를 한 장으로 — 12종 템플릿.", price:2400, likes:64, views:"480", thumb:"storyboard" },
  { id:"v17", cat:"콘텐츠", tag:"스토리보드", tool:"Claude 4.5 Sonnet", title:"음악 뮤직비디오 컨셉",
    desc:"곡 분위기에 맞춘 시각 컨셉 + 8컷 스토리보드.", price:5400, likes:128, views:"880", thumb:"storyboard" },
  { id:"v18", cat:"콘텐츠", tag:"유튜브", tool:"GPT-4o", title:"유튜브 채널 콘셉트 기획",
    desc:"채널 아이덴티티 + 4주 콘텐츠 캘린더.", price:3900, likes:88, views:"640", thumb:"storyboard" },
  { id:"v19", cat:"콘텐츠", tag:"틱톡", tool:"Claude 4.5 Haiku", title:"틱톡 콘텐츠 아이디어 30종",
    desc:"브랜드별 — 즉시 촬영 가능한 아이디어 풀.", price:1900, likes:286, views:"2.3K", thumb:"storyboard" },
  { id:"v20", cat:"콘텐츠", tag:"강의", tool:"Claude 4.5 Sonnet", title:"e북 전자책 구성안",
    desc:"100페이지 전자책 — 챕터 + 핵심 메시지 + 디자인 가이드.", price:3400, likes:78, views:"560", thumb:"storyboard" },
];

window.PORTFOLIO_ITEMS = PORTFOLIO_ITEMS;

// Generic teaser/locked prompt — fallback for all items
window.PORTFOLIO_PROMPT_DEFAULT = {
  teaser:
`You are a world-class creator specialized in {category} work.
Given the brief below, produce a complete, production-ready deliverable in Korean context.

Brief: {description}

Detailed instructions:`,
  locked:
`
1. Audience: Korean professional, primary device mobile, English fluent
2. Tone: warm yet authoritative, no corporate buzzwords, conversational
3. Constraints: respect brand guidelines, include 3 variants for A/B testing,
   provide editable building blocks (not just final output)
4. Format: structured output with headings — each section labeled
   clearly, examples in code blocks where applicable
5. Length: optimized for the deliverable — never padded
6. Quality bar: every line must justify its presence; remove fluff
7. Localization: Korean primary, mix 1-2 English accent words sparingly
8. Output: ready to use as-is, no further editing required

Constraints (technical):
- Avoid clichés, generic phrasing, AI-tells
- Include 2 alternate approaches at the end as "B-side options"
- Reference cultural specificity where relevant
- Cite measurement: how to evaluate success of this deliverable

Now execute, producing the highest-quality work you are capable of.`,
};
